### ISSUE TITLE
Events Page

### ISSUE THREAD

**Issue by phoenixpereira** [compsci-adl/website#20]
Create sections required for the events page.

### Tasks:

**Sections**

- [ ] Friday Night Games
- [ ] Duck Lounge
- [ ] Image carousel of images from different events
- [ ] Upcoming Events

**Components**

- [ ] Events list (method to be determined, either use an API to get events from our Facebook page or manually add to the database)
