### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by phoenixpereira** [compsci-adl/website#22]
Create sections required for the contact page.

### Tasks:

**Sections**

- [ ] Want to get in touch?
- [ ] Social media media icon links
- [ ] Competitions & Projects
- [ ] For sponsorships
- [ ] Contact us form
- [ ] FAQ

**Components**

- [ ] Contact us form
