### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by phoenixpereira** [compsci-adl/website#6]
Create essential frontend components required for the homepage and the overall website

### Tasks:

**Components**
   - [x] Header
   - [x] Footer
   - [x] Grid
   - [x] Image carousel
   - [x] Button
   - [ ] Upcoming Events

**Miscellaneous:**
   - [x] Use the duck silhouette as the favicon for the site
   - [x] Make site mobile friendly/responsive 
   - [x] Add icons
   - [x] Add custom fonts
